## ChatGpt Automation test Codes
### 모두를 위한 ChatGpt Part2 - Numpy & Pandas

In [56]:
import numpy as np

array_1dimension = np.array([1, 2, 3, 4])

array_2dimension = np.array([[1,2,3,4], [5,6,7,8]])

array_3dimension = np.array([[[1,2,3,4], [5,6,7,8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
# 3차원 배열과 shape을 출력. 
print(array_2dimension)
print(array_2dimension.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [44]:
# 0 / 1/ random 으로 채운 array 만들기 
zeros = np.zeros([18])
ones = np.ones([18, 2])
randoms = np.random.randn(4,4).round(2)
randoms

array([[ 1.03,  0.35,  1.55, -1.57],
       [-0.91,  1.3 ,  0.83,  0.71],
       [-1.74,  1.23,  0.6 ,  0.98],
       [-0.75, -0.7 , -0.62, -0.96]])

#### indexing & slicing
다차원 배열의 경우 indexing과 slicing을 섞어서 원하는 요소에 접근할 수 있음 

In [48]:
randoms[0, 1]
randoms[0][1]
randoms[0][1:3]

array([0.35, 1.55])

#### broadcasting & aggregation 
broadcasting : 사칙연산 시 전체 원소에 동일하게 적용 
aggregation : sum, mean(평균), prod(곱), max, min, argmax(max위치), argmin(min위치) 

In [50]:
array_1dimension.sum(), array_1dimension.mean(), array_1dimension.prod(), array_1dimension.max(), array_1dimension.min(), array_1dimension.argmax(), array_1dimension.argmin()

(10, 2.5, 24, 4, 1, 3, 0)

In [55]:
array_2dimension.sum(axis=0), array_2dimension.sum(axis=1)

(array([ 6,  8, 10, 12]), array([10, 26]))